import slugify from '../utils/slugify'

export default {
  title: "News Articles",
  name: 'news',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this release",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Post Date",
      description: "Press the button to the right to pick a date.",
      name: "date",
      type: "date",
      options: {
        dateFormat: "MMMM Do YYYY",
      },
      validation: Rule => Rule.required()
    },
    {
      title: "Teaser Image",
      name: "teaserImage",
      description: "The image that appears in the news listing",
      type: "image",
      validation: Rule => Rule.required()
    },
    {
      title: 'Content Blocks',
      name: 'contentBlocks',
      description: 'The modular content blocks for this article',
      type: 'array',
      of: [
        {type: 'contentFull', title: 'Content (100% Width)'},
        {type: 'halfContent', title: 'Content (50%/50% Width)'},
        {type: 'tourDates', title: 'Tour Dates'},
        {type: 'image', title: 'Image'},
        {type: 'heading', title: 'Heading Title'}
      ],
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: 'title',
        maxLength: 96,
        slugify: title => slugify(title)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ]
}